# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
[$username@$hostname](bold green):$directory$python
[>](blue) 
"""

right_format = "$status"

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[username]
format = '$user'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '$hostname'
disabled = false

[directory]
style = "yellow"
truncation_length = 8
truncation_symbol = '…/'
read_only = ""

[status]
symbol = "↵"
recognize_signal_code = false
disabled = false
style = "bold red"
format = "[$int $symbol]($style)"

[python]
style = "white"
format = '[(\($virtualenv\) )]($style)'
pyenv_version_name = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true