"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[$username@$hostname](bold green):$directory$python
$character
"""

right_format = "$status"


[character]
success_symbol = '[>](blue)'
error_symbol = '[>](red)'

[username]
format = '$user'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '$hostname'
disabled = false

[directory]
style = "yellow"
truncation_length = 8
truncation_symbol = '…/'
read_only = ""

[status]
symbol = "↵"
recognize_signal_code = false
disabled = false
style = "bold red"
format = "[$int $symbol]($style)"

[python]
style = "white"
format = '[(\($virtualenv\) )]($style)'
pyenv_version_name = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true