vim.cmd([[:tnoremap <C-\><Esc> <C-\><C-n><Cmd>:FloatermHide<CR>]])
vim.cmd([[:noremap <C-\><Esc> <Cmd>:FloatermToggle<CR>]])
vim.cmd([[:noremap <S-Tab> <Cmd>:BufferPrevious<CR>]])
vim.cmd([[:noremap <Tab> <Cmd>:BufferNext<CR>]])
vim.cmd([[:noremap <C-j> <Cmd>:NvimTreeFocus<CR>]])
